site_name: wrappers
site_url: https://supabase.github.io/wrappers
site_description: A PostgreSQL extension for connecting to external data sources

repo_name: supabase/wrappers
repo_url: https://github.com/supabase/wrappers

nav:
    - Home:  
        - 'index.md'
    - Catalog: 
        - catalog/index.md
        - Airtable: 'catalog/airtable.md'
        - Auth0: 'catalog/auth0.md'
        - AWS Cognito: 'catalog/cognito.md'
        - BigQuery: 'catalog/bigquery.md'
        - ClickHouse: 'catalog/clickhouse.md'
        - Firebase: 'catalog/firebase.md'
        - Logflare: 'catalog/logflare.md'
        - Notion: 'catalog/notion.md'
        - Paddle: 'catalog/paddle.md'
        - Redis: 'catalog/redis.md'
        - S3 (CSV, JSON, Parquet): 'catalog/s3.md'
        - Snowflake: 'catalog/snowflake.md'
        - Stripe: 'catalog/stripe.md'
        - SQL Server: 'catalog/mssql.md'
    - Guides:
        - Native vs Wasm Wrappers: 'guides/native-wasm.md'
        - Installing Wrappers in Postgres: 'guides/installation.md'
        - Limitations: 'guides/limitations.md'
    - Contributing: 
       - Core Development: 'contributing/core.md'
       - Developing a Native Wrapper: 'contributing/native.md'
       - Developing a Wasm Wrapper: 'contributing/wasm.md'
       - Documentation: 'contributing/documentation.md'

plugins:
  - tags:
      tags_file: tags.md

theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/wrappers
    features:
      - navigation.expand  
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.indexes
    palette:
        scheme: slate
        primary: black
        accent: light blue

extra_css:
    - stylesheets/extra.css


markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
